In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [2]:
conn = sqlite3.connect(r"E:\Valorant-Esports-Data-Pipeline-for-Analytics-and-Machine-Learning\data\valorant.db")
cursor = conn.cursor()

## Data Profiling

In [3]:
tours_df = pd.read_parquet(r"E:\Valorant-Esports-Data-Pipeline-for-Analytics-and-Machine-Learning\data\raw\tours.parquet")
tours_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   tour_id      48 non-null     object
 1   tour_name    48 non-null     object
 2   tour_tag     48 non-null     object
 3   tour_stage   48 non-null     object
 4   tour_region  48 non-null     object
 5   tour_status  48 non-null     object
dtypes: object(6)
memory usage: 2.4+ KB

In [10]:
tours_df[tours_df["tour_id"] == "1998"]

,tour_id,tour_name,tour_tag,tour_stage,tour_region,tour_status
18,1998,Champions Tour 2024: EMEA Stage 1,Valorant Champions Tour 2024,Stage 1,EMEA,completed

In [4]:
tours_df.duplicated().sum()

np.int64(0)

In [5]:
tours_df.isna().sum()

tour_id        0
tour_name      0
tour_tag       0
tour_stage     0
tour_region    0
tour_status    0
dtype: int64

In [6]:
tours_df["tour_stage"].unique()

array(['Last Chance Qualifier', 'Stage 1', 'Stage 2', 'Kickoff',
       'Champions', 'Shanghai', 'Masters', 'Madrid'], dtype=object)

In [7]:
tours_df[tours_df["tour_stage"] == "Last Chance Qualifier"]

,tour_id,tour_name,tour_tag,tour_stage,tour_region,tour_status
0,1659,Champions Tour 2023: EMEA Last Chance Qualifier,Valorant Champions Tour 2023,Last Chance Qualifier,EMEA,completed
12,1658,Champions Tour 2023: Americas Last Chance Qual...,Valorant Champions Tour 2023,Last Chance Qualifier,Americas,completed

In [8]:
tours_df[tours_df["tour_stage"] == "Madrid"]

,tour_id,tour_name,tour_tag,tour_stage,tour_region,tour_status
30,1921,Champions Tour 2024: Masters Madrid,Valorant Champions Tour 2024,Madrid,Masters,completed

In [9]:
tours_df["tour_region"].unique()

array(['EMEA', 'China', 'Pacific', 'Americas', 'World', 'Masters'],
      dtype=object)

In [10]:
tours_df["tour_tag"].unique()

array(['Valorant Champions Tour 2023', 'Valorant Champions Tour 2025',
       'Valorant Champions Tour 2026', 'Valorant Champions Tour 2024'],
      dtype=object)

In [11]:
tours_df["tour_status"].unique()

array(['completed', 'upcoming', 'ongoing'], dtype=object)

**Insight**

- Since only Masters stage has different name format and make tour_stage naming looks messy, replace tour_stage value out of stage keyword with "Masters".
- Master stage are competition across region so, it must define they tour_region as "all".
- Last Chance Qualifier was VCT tournament format before 2024.

In [5]:
matches_df = pd.read_parquet(r"E:\Valorant-Esports-Data-Pipeline-for-Analytics-and-Machine-Learning\data\raw\matches.parquet")
matches_df.describe()

,tour_id,home_score,away_score,home_h2h_win,away_h2h_win,home_h2h_score,away_h2h_score,home_n_last_win,away_n_last_win,home_n_last_match,away_n_last_match
count,1259.000000,1259.000000,1259.000000,1259.00000,1259.000000,1259.000000,1259.000000,1259.000000,1259.000000,1259.000000,1259.000000
mean,2309.656871,1.294678,1.266084,1.93884,1.717236,4.731533,4.412232,2.710087,2.544083,4.993646,4.989674
std,316.893918,0.894993,0.888838,2.12306,2.028285,4.949929,4.807176,1.222855,1.208181,0.154295,0.175769
min,1657.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2006.000000,0.000000,0.000000,0.00000,0.000000,1.000000,1.000000,2.000000,2.000000,5.000000,5.000000
50%,2283.000000,2.000000,1.000000,1.00000,1.000000,4.000000,3.000000,3.000000,3.000000,5.000000,5.000000
75%,2501.000000,2.000000,2.000000,3.00000,3.000000,7.000000,6.000000,4.000000,3.000000,5.000000,5.000000
max,2864.000000,3.000000,3.000000,12.00000,15.000000,29.000000,34.000000,5.000000,5.000000,5.000000,5.000000

In [11]:
matches_df[matches_df["match_id"] == "71902"]

,tour_id,match_id,date,bracket,home_name,home_alias,away_name,away_alias,bo,home_score,away_score,home_h2h_win,away_h2h_win,home_h2h_score,away_h2h_score,home_n_last_win,away_n_last_win,home_n_last_match,away_n_last_match,patch
666,1998,71902,2024-04-04 11:00:00,Regular Season: Week 1,Team Vitality,VIT,Natus Vincere,NAVI,Bo3,0,2,0,2,0,4,3,4,5,5,8.05

In [5]:
matches_df.head()

,tour_id,match_id,date,bracket,home_name,home_alias,away_name,away_alias,bo,home_score,away_score,home_h2h_win,away_h2h_win,home_h2h_score,away_h2h_score,home_n_last_win,away_n_last_win,home_n_last_match,away_n_last_match,patch
0,2498,95056,2025-07-16 11:00:00,Group Stage: Week 1,Natus Vincere,NAVI,Apeks,APK,Bo3,2,1,1,0,2,1,3,0,5,5,11.0
1,2498,95057,2025-07-16 13:50:00,Group Stage: Week 1,Team Vitality,VIT,GIANTX,GX,Bo3,0,2,3,0,6,2,1,2,5,5,11.0
2,2498,95058,2025-07-17 11:00:00,Group Stage: Week 1,FUT Esports,FUT,Gentle Mates,M8,Bo3,2,1,2,0,4,1,2,4,5,5,11.0
3,2498,95059,2025-07-17 14:30:00,Group Stage: Week 1,Team Liquid,TL,KOI,MKOI,Bo3,2,1,5,1,11,4,1,1,5,5,11.0
4,2498,95060,2025-07-18 11:00:00,Group Stage: Week 1,Team Heretics,TH,BBL Esports,BBL,Bo3,2,1,3,2,7,4,5,4,5,5,11.0

In [14]:
matches_df.duplicated().sum()

np.int64(0)

In [15]:
matches_df.isna().sum()

tour_id                0
match_id               0
date                   0
bracket                0
home_name              0
home_alias             0
away_name              0
away_alias             0
bo                     0
home_score             0
away_score             0
home_h2h_win           0
away_h2h_win           0
home_h2h_score         0
away_h2h_score         0
home_n_last_win        0
away_n_last_win        0
home_n_last_match      0
away_n_last_match      0
home_n_last_wr         0
away_n_last_wr         0
patch                266
dtype: int64

In [16]:
matches_df["patch"].unique()

array(['11.0', '10.05', '10.06', '10.07', '10.08', None, '9.0', '10.02',
       '8.02', '8.03', '8.10', '8.11', '8.04', '12.05', '12.06', '12.07',
       '12.08', '12.0', '8.05', '8.07', '10.0', '10.01', '7.02', '8.09',
       '9.02', '7.0', '10.10', '11.05', '12.03'], dtype=object)

**Insight**

- Match general statistic looks clean but, map statitistic looks messy. Separate map statitistic from match general statistic on scraper(recommended) or bronze layer.
- Patch NaN values due to data unavailable from scraping source. Dropping should be recommended for model but need to consider for trend analyze.

In [17]:
games_ovw_df = pd.read_parquet(r"E:\Valorant-Esports-Data-Pipeline-for-Analytics-and-Machine-Learning\data\raw\games_overview.parquet")
games_ovw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3224 entries, 0 to 3223
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   match_id        3224 non-null   object
 1   game_id         3224 non-null   object
 2   game_map        3224 non-null   object
 3   game_duration   2820 non-null   object
 4   home_score      3224 non-null   int64
 5   away_score      3224 non-null   int64
 6   home_atk_score  3223 non-null   float64
 7   away_atk_score  3223 non-null   float64
 8   home_def_score  3223 non-null   float64
 9   away_def_score  3223 non-null   float64
 10  home_ot_score   353 non-null    float64
 11  away_ot_score   353 non-null    float64
dtypes: float64(6), int64(2), object(4)
memory usage: 302.4+ KB

In [18]:
games_ovw_df.describe()

,home_score,away_score,home_atk_score,away_atk_score,home_def_score,away_def_score,home_ot_score,away_ot_score
count,3224.000000,3224.000000,3223.000000,3223.000000,3223.00000,3223.000000,353.000000,353.000000
mean,10.700993,10.489144,5.470059,5.328266,5.23022,5.162581,1.821530,2.042493
std,3.362371,3.535802,2.491379,2.559212,2.58218,2.578188,1.710393,1.758391
min,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,8.000000,8.000000,4.000000,4.000000,3.00000,3.000000,0.000000,0.000000
50%,13.000000,13.000000,5.000000,5.000000,5.00000,5.000000,2.000000,2.000000
75%,13.000000,13.000000,7.000000,7.000000,7.00000,7.000000,3.000000,3.000000
max,25.000000,23.000000,14.000000,14.000000,14.00000,14.000000,13.000000,11.000000

In [19]:
games_ovw_df.duplicated().sum()

np.int64(0)

In [20]:
games_ovw_df[games_ovw_df["home_atk_score"].isna()]

,match_id,game_id,game_map,game_duration,home_score,away_score,home_atk_score,away_atk_score,home_def_score,away_def_score,home_ot_score,away_ot_score
180,87871,214836,Split,None,13,6,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
games_econ_df = pd.read_parquet(r"E:\Valorant-Esports-Data-Pipeline-for-Analytics-and-Machine-Learning\data\raw\games_economy.parquet")
games_econ_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3941 entries, 0 to 3940
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             3941 non-null   object
 1   game_id              3941 non-null   object
 2   home_pstl_win        2455 non-null   float64
 3   away_pstl_win        2455 non-null   float64
 4   home_eco_round       2455 non-null   float64
 5   away_eco_round       2455 non-null   float64
 6   home_eco_win         2455 non-null   float64
 7   away_eco_win         2455 non-null   float64
 8   home_semi_eco_round  2455 non-null   float64
 9   away_semi_eco_round  2455 non-null   float64
 10  home_semi_eco_win    2455 non-null   float64
 11  away_semi_eco_win    2455 non-null   float64
 12  home_semi_buy_round  2455 non-null   float64
 13  away_semi_buy_round  2455 non-null   float64
 14  home_semi_buy_win    2455 non-null   float64
 15  away_semi_buy_win    2455 non-null   float64
 16  home_full_buy_round  2455 non-null   float64
 17  away_full_buy_round  2455 non-null   float64
 18  home_full_buy_win    2455 non-null   float64
 19  away_full_buy_win    2455 non-null   float64
dtypes: float64(18), object(2)
memory usage: 615.9+ KB

In [22]:
games_econ_df.describe()

,home_pstl_win,away_pstl_win,home_eco_round,away_eco_round,home_eco_win,away_eco_win,home_semi_eco_round,away_semi_eco_round,home_semi_eco_win,away_semi_eco_win,home_semi_buy_round,away_semi_buy_round,home_semi_buy_win,away_semi_buy_win,home_full_buy_round,away_full_buy_round,home_full_buy_win,away_full_buy_win
count,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000,2455.000000
mean,1.010183,0.989817,3.024033,3.038697,1.123829,1.086762,1.132383,1.140937,0.256619,0.242363,4.873727,5.011813,2.492464,2.499389,12.220367,12.059063,6.845621,6.703462
std,0.702407,0.702407,0.735518,0.734338,0.721753,0.710418,0.976074,0.990837,0.494604,0.482284,2.310711,2.419752,1.420196,1.470679,3.703991,3.878053,3.081115,3.236666
min,0.000000,0.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,3.000000,3.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,1.000000,1.000000,10.000000,10.000000,5.000000,4.000000
50%,1.000000,1.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,5.000000,5.000000,2.000000,2.000000,12.000000,12.000000,7.000000,7.000000
75%,2.000000,1.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,6.000000,7.000000,3.000000,3.000000,14.000000,14.000000,9.000000,9.000000
max,2.000000,2.000000,6.000000,6.000000,4.000000,3.000000,5.000000,6.000000,3.000000,3.000000,14.000000,15.000000,8.000000,9.000000,38.000000,39.000000,20.000000,20.000000

**Insight**

- Difference total row between games overview and economy due to unplayed map still recorded and save as NaN values except game_id and map_name.
- NaN values due to data unavailable from scraping source.

In [23]:
players_df = pd.read_parquet(r"E:\Valorant-Esports-Data-Pipeline-for-Analytics-and-Machine-Learning\data\raw\players.parquet")
players_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96720 entries, 0 to 96719
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   game_id      96720 non-null  object
 1   name         96720 non-null  object
 2   team_alias   96720 non-null  object
 3   nationality  96720 non-null  object
 4   agent        96720 non-null  object
 5   mod          96720 non-null  object
 6   r            84510 non-null  float64
 7   acs          88544 non-null  float64
 8   k            88740 non-null  float64
 9   d            88740 non-null  float64
 10  a            88740 non-null  float64
 11  kd           88728 non-null  float64
 12  kast         84625 non-null  float64
 13  adr          86023 non-null  float64
 14  hs           86145 non-null  float64
 15  fk           86120 non-null  float64
 16  fd           86123 non-null  float64
 17  fkfd         86123 non-null  float64
dtypes: float64(12), object(6)
memory usage: 13.3+ MB

In [24]:
players_df.describe()

,r,acs,k,d,a,kd,kast,adr,hs,fk,fd,fkfd
count,84510.000000,88544.000000,88740.000000,88740.000000,88740.000000,88728.000000,84625.000000,86023.000000,86145.000000,86120.000000,86123.000000,86123.000000
mean,0.997946,197.061935,10.003268,10.013568,4.097611,-0.010301,71.640721,129.050835,29.272285,1.424733,1.424799,-0.000116
std,0.423323,72.686833,5.613167,4.640909,3.252632,4.904942,14.866450,50.930850,12.875256,1.482239,1.432729,1.762032
min,0.010000,-6.000000,-1.000000,0.000000,0.000000,-21.000000,8.000000,-5548.000000,0.000000,0.000000,-1.000000,-14.000000
25%,0.710000,148.000000,6.000000,7.000000,2.000000,-3.000000,63.000000,98.000000,21.000000,0.000000,0.000000,-1.000000
50%,0.980000,191.000000,9.000000,9.000000,3.000000,0.000000,73.000000,126.000000,28.000000,1.000000,1.000000,0.000000
75%,1.250000,240.000000,13.000000,13.000000,6.000000,3.000000,83.000000,157.000000,36.000000,2.000000,2.000000,1.000000
max,5.400000,1082.000000,47.000000,41.000000,28.000000,28.000000,100.000000,3155.000000,100.000000,12.000000,15.000000,11.000000

**Insight**

- Invalid values has recorded such a(Average Combat Score), k(Kills), adr(Average Damage per Round), and fd(First-Death).
- NaN values due to data unavailable from scraping source.

In [25]:
map_vetos_df = pd.read_parquet(r"E:\Valorant-Esports-Data-Pipeline-for-Analytics-and-Machine-Learning\data\raw\map_vetos.parquet")
map_vetos_df['match_id'] = map_vetos_df['match_id'].astype('str')
map_vetos_df.to_parquet(r"E:\Valorant-Esports-Data-Pipeline-for-Analytics-and-Machine-Learning\data\raw\map_vetos.parquet")
map_vetos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8814 entries, 0 to 8813
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   match_id   8814 non-null   object
 1   map_name   8814 non-null   object
 2   team_name  7554 non-null   object
 3   action     8814 non-null   object
dtypes: object(4)
memory usage: 275.6+ KB

**Insight**

- NaN values represent decider map does not determined by both of team.

In [26]:
tours_df.to_sql("bronze_tours", conn, if_exists="replace", index=False)
matches_df.to_sql("bronze_matches", conn, if_exists="replace", index=False)
games_ovw_df.to_sql("bronze_games_overview", conn, if_exists="replace", index=False)
games_econ_df.to_sql("bronze_games_economy", conn, if_exists="replace", index=False)
players_df.to_sql("bronze_players", conn, if_exists="replace", index=False)
map_vetos_df.to_sql("bronze_map_vetos", conn, if_exists="replace", index=False)

8814

## Data Cleaning and Transformation

In [28]:
tours_df = tours_df.replace({"tour_stage": {"Madrid": "Masters", "Shanghai": "Masters"}, "tour_region": {"Masters": "World"}})
tours_df.tail()

,tour_id,tour_name,tour_tag,tour_stage,tour_region,tour_status
43,2005,Champions Tour 2024: Pacific Stage 2,Valorant Champions Tour 2024,Stage 2,Pacific,completed
44,2864,VCT 2026: China Stage 1,Valorant Champions Tour 2026,Stage 1,China,completed
45,2004,Champions Tour 2024: Americas Stage 1,Valorant Champions Tour 2024,Stage 1,Americas,completed
46,2283,Valorant Champions 2025,Valorant Champions Tour 2025,Champions,World,completed
47,2498,VCT 2025: EMEA Stage 2,Valorant Champions Tour 2025,Stage 2,EMEA,completed

In [29]:
matches_df["date"] = pd.to_datetime(matches_df["date"])
matches_df.head()

,tour_id,match_id,date,bracket,home_name,home_alias,away_name,away_alias,bo,home_score,...,away_h2h_win,home_h2h_score,away_h2h_score,home_n_last_win,away_n_last_win,home_n_last_match,away_n_last_match,home_n_last_wr,away_n_last_wr,patch
0,2498,95056,2025-07-16 11:00:00,Group Stage: Week 1,Natus Vincere,NAVI,Apeks,APK,Bo3,2,...,0,2,1,3,0,5,5,0.6,0.0,11.0
1,2498,95057,2025-07-16 13:50:00,Group Stage: Week 1,Team Vitality,VIT,GIANTX,GX,Bo3,0,...,0,6,2,1,2,5,5,0.2,0.4,11.0
2,2498,95058,2025-07-17 11:00:00,Group Stage: Week 1,FUT Esports,FUT,Gentle Mates,M8,Bo3,2,...,0,4,1,2,4,5,5,0.4,0.8,11.0
3,2498,95059,2025-07-17 14:30:00,Group Stage: Week 1,Team Liquid,TL,KOI,MKOI,Bo3,2,...,1,11,4,1,1,5,5,0.2,0.2,11.0
4,2498,95060,2025-07-18 11:00:00,Group Stage: Week 1,Team Heretics,TH,BBL Esports,BBL,Bo3,2,...,2,7,4,5,4,5,5,1.0,0.8,11.0

In [30]:
def duration_time(value):        
    if ":" in value:
        game_duration = value.split(":")
        if len(game_duration) > 2:
            duration = (int(game_duration[0]) * 60) + int(game_duration[1]) + (int(game_duration[2]) / 60)
        else:
            duration = int(game_duration[0]) + (int(game_duration[1]) / 60)
        
        return duration
    
    else:
        return np.nan

In [31]:
games_ovw_df["game_duration"] = games_ovw_df["game_duration"].astype(str).apply(duration_time).round(2)
games_ovw_df["game_map"] = [i.replace("-", "") for i in games_ovw_df["game_map"]]
games_ovw_df.head()

,match_id,game_id,game_map,game_duration,home_score,away_score,home_atk_score,away_atk_score,home_def_score,away_def_score,home_ot_score,away_ot_score
0,95056,226424,Icebox,37.88,13,4,3.0,2.0,10.0,2.0,NaN,NaN
1,95056,226425,Sunset,40.00,6,13,4.0,5.0,2.0,8.0,NaN,NaN
2,95056,226426,Corrode,37.05,13,3,9.0,0.0,4.0,3.0,NaN,NaN
3,95057,226427,Sunset,51.33,10,13,6.0,7.0,4.0,6.0,NaN,NaN
4,95057,226428,Bind,52.45,11,13,5.0,6.0,6.0,7.0,NaN,NaN

In [32]:
tours_df.to_sql(
    "silver_tours",
    conn,
    if_exists="replace",
    index=False
)

48

In [33]:
matches_df.to_sql(
    "silver_matches",
    conn,
    if_exists="replace",
    index=False
)

1259

In [34]:
games_ovw_df.to_sql(
    "silver_games_overview",
    conn,
    if_exists="replace",
    index=False
)

3224

In [35]:
games_econ_df.to_sql(
    "silver_games_economy",
    conn,
    if_exists="replace",
    index=False
)

3941

In [36]:
map_vetos_df.to_sql(
    "silver_map_vetos",
    conn,
    if_exists="replace",
    index=False
)

8814

In [37]:
players_df.to_sql(
    "silver_players",
    conn,
    if_exists="replace",
    index=False
)

96720

In [38]:
query = """
WITH team_list AS (
    SELECT
        t.tour_region AS team_region,
        m.home_name AS team_name,
        m.home_alias AS team_alias
    FROM silver_matches AS m
    JOIN silver_tours as t
    ON m.tour_id = t.tour_id
    UNION
    SELECT
        t.tour_region,
        m.away_name,
        m.away_alias
    FROM silver_matches AS m
    JOIN silver_tours AS t
    ON m.tour_id = t.tour_id
),

unique_team AS (
    SELECT DISTINCT
        team_name,
        team_alias,
        team_region
    FROM team_list
)

SELECT 
    ROW_NUMBER() OVER (ORDER BY team_name) AS team_id,
    team_name,
    team_alias,
    team_region
FROM unique_team
WHERE NOT team_region = "World"
"""

df = pd.read_sql(query, conn)
df.tail()

    team_id       team_name team_alias team_region
51       52     ULF Esports        ULF        EMEA
52       53          VARREL         VL     Pacific
53       54  Wolves Esports        WOL       China
54       55   Xi Lai Gaming        XLG       China
55       56   ZETA DIVISION       ZETA     Pacific

In [39]:
df.to_sql(
    "silver_dims_teams",
    conn,
    if_exists="replace",
    index=False
)

56

In [40]:
query = """
WITH map_list AS (
    SELECT DISTINCT m.map_name AS map_name
    FROM silver_map_vetos as m
)
SELECT ROW_NUMBER() OVER (ORDER BY map_name) AS map_id, map_name
FROM map_list
"""

df = pd.read_sql(query, conn)
df

    map_id  map_name
0        1     Abyss
1        2    Ascent
2        3      Bind
3        4    Breeze
4        5   Corrode
5        6  Fracture
6        7     Haven
7        8    Icebox
8        9     Lotus
9       10     Pearl
10      11     Split
11      12    Sunset

In [41]:
df.to_sql(
    "silver_dims_maps",
    conn,
    if_exists="replace",
    index=False
)

12

In [42]:
query = """
WITH player_list AS (
SELECT DISTINCT
    name AS player_name,
    nationality AS player_nationality
FROM silver_players p
)
SELECT ROW_NUMBER () OVER (ORDER BY player_name) AS player_id, player_name, player_nationality
FROM player_list
;
"""

df = pd.read_sql(query, conn)
df

     player_id player_name player_nationality
0            1         2GE        Philippines
1            2         5CM              China
2            3       AAAAY              China
3            4         AAK              China
4            5          AC              China
..         ...         ...                ...
493        494       yuran              Japan
494        495      zander             Canada
495        496      zekken      United States
496        497         zhe              China
497        498         zjc              China

[498 rows x 3 columns]

In [43]:
df.to_sql(
    "silver_dims_players",
    conn,
    if_exists="replace",
    index=False
)

498

In [49]:
query = """
SELECT
    tour_id,
    match_id,
    date,
    bracket,
    t1.team_id AS home_team_id,
    t2.team_id AS away_team_id,
    p.patch_id,
    bo,
    home_score,
    away_score,
    home_h2h_win,
    away_h2h_win,
    home_h2h_score,
    away_h2h_score,
    home_n_last_win, 
    away_n_last_win,
    home_n_last_match,
    away_n_last_match,
    home_n_last_wr, -- need to update
    away_n_last_wr -- need to update
FROM silver_matches m
JOIN silver_dims_teams t1
ON home_name = t1.team_name
JOIN silver_dims_teams t2
ON away_name = t2.team_name
JOIN silver_dims_patches p
ON m.patch = p.patch;
"""

df = pd.read_sql(query, conn)
df.head()

,tour_id,match_id,date,bracket,home_team_id,away_team_id,patch_id,bo,home_score,away_score,home_h2h_win,away_h2h_win,home_h2h_score,away_h2h_score,home_n_last_win,away_n_last_win,home_n_last_match,away_n_last_match,home_n_last_wr,away_n_last_wr
0,2498,95056,2025-07-16 11:00:00,Group Stage: Week 1,36,4,9,Bo3,2,1,1,0,2,1,3,0,5,5,0.6,0.0
1,2498,95057,2025-07-16 13:50:00,Group Stage: Week 1,49,22,9,Bo3,0,2,3,0,6,2,1,2,5,5,0.2,0.4
2,2498,95058,2025-07-17 11:00:00,Group Stage: Week 1,19,24,9,Bo3,2,1,2,0,4,1,2,4,5,5,0.4,0.8
3,2498,95059,2025-07-17 14:30:00,Group Stage: Week 1,47,29,9,Bo3,2,1,5,1,11,4,1,1,5,5,0.2,0.2
4,2498,95060,2025-07-18 11:00:00,Group Stage: Week 1,46,5,9,Bo3,2,1,3,2,7,4,5,4,5,5,1.0,0.8

In [45]:
df.to_sql(
    "silver_fact_matches",
    conn,
    if_exists="replace",
    index=False
)

956

In [53]:
query = """
SELECT
    m.tour_id,
    o.match_id,
    o.game_id,
    ma.map_id,
    m.home_team_id,
    m.away_team_id,
    game_duration,
    o.home_score,
    o.away_score,
    o.home_atk_score,
    o.away_atk_score,
    o.home_def_score,
    o.away_def_score,
    o.home_ot_score,
    o.away_ot_score,
    e.home_pstl_win,
    e.away_pstl_win,
    e.home_eco_round,
    e.away_eco_round,
    e.home_eco_win,
    e.away_eco_win,
    e.home_semi_eco_round,
    e.away_semi_eco_round,
    e.home_semi_eco_win,
    e.away_semi_eco_win,
    e.home_semi_buy_round,
    e.away_semi_buy_round,
    e.home_semi_buy_win,
    e.away_semi_buy_win,
    e.home_full_buy_round,
    e.away_full_buy_round,
    e.home_full_buy_win,
    e.away_full_buy_win
FROM silver_games_overview o
INNER JOIN silver_games_economy e
ON o.game_id = e.game_id
JOIN silver_dims_maps ma
ON o.game_map = ma.map_name
JOIN silver_fact_matches m
ON o.match_id = m.match_id
"""

df = pd.read_sql(query, conn)
df.head()

,tour_id,match_id,game_id,map_id,home_team_id,away_team_id,game_duration,home_score,away_score,home_atk_score,...,home_semi_eco_win,away_semi_eco_win,home_semi_buy_round,away_semi_buy_round,home_semi_buy_win,away_semi_buy_win,home_full_buy_round,away_full_buy_round,home_full_buy_win,away_full_buy_win
0,2498,95056,226424,8,36,4,37.88,13,4,3.0,...,1.0,0.0,2.0,8.0,1.0,2.0,11.0,4.0,10.0,1.0
1,2498,95056,226425,12,36,4,40.00,6,13,4.0,...,0.0,1.0,3.0,6.0,1.0,5.0,11.0,10.0,5.0,5.0
2,2498,95056,226426,5,36,4,37.05,13,3,9.0,...,0.0,0.0,3.0,6.0,3.0,2.0,11.0,4.0,8.0,1.0
3,2498,95057,226427,12,49,22,51.33,10,13,6.0,...,0.0,1.0,6.0,1.0,5.0,1.0,13.0,17.0,3.0,11.0
4,2498,95057,226428,3,49,22,52.45,11,13,5.0,...,0.0,1.0,4.0,10.0,2.0,5.0,16.0,10.0,8.0,6.0

In [54]:
df.to_sql(
    "silver_fact_games",
    conn,
    if_exists="replace",
    index=False
)

2455

In [75]:
query = """
WITH agent_list AS (
    SELECT DISTINCT agent AS agent_name
    FROM silver_players
)
SELECT ROW_NUMBER() OVER (ORDER BY agent_name) AS agent_id, agent_name
FROM agent_list;
"""

df = pd.read_sql(query, conn)
df.tail()

    agent_id agent_name
24        25       Veto
25        26      Viper
26        27       Vyse
27        28     Waylay
28        29       Yoru

In [111]:
df.to_sql(
    "silver_dims_agents",
    conn,
    if_exists="replace",
    index=False
)

29

In [45]:
query = """
WITH colomn_key AS (
    SELECT
        m.tour_id,
        g.match_id,
        game_id
    FROM silver_games g
    JOIN silver_matches m
    ON g.match_id = m.match_id
)
SELECT
    c.tour_id,
    c.match_id,
    p.game_id,
    dp.player_id,
    t.team_id,
    a.agent_id,
    mod,
    r,
    acs,
    k,
    d,
    a,
    kd,
    kast,
    adr,
    hs,
    fk,
    fd,
    fkfd
FROM silver_players p
JOIN colomn_key c
ON p.game_id = c.game_id
JOIN silver_dims_teams t
ON p.team_alias = t.team_alias
JOIN silver_dims_players dp
ON p.name = dp.player_name
JOIN silver_dims_agents a
ON p.agent = a.agent_name
"""

df = pd.read_sql(query, conn)
df.head()

,tour_id,match_id,game_id,player_id,team_id,agent_id,mod,r,acs,k,d,a,kd,kast,adr,hs,fk,fd,fkfd
0,2498,95056,226424,351,36,14,avg,1.69,284.0,19.0,7.0,3.0,12.0,76.0,183.0,39.0,4.0,2.0,2.0
1,2498,95056,226424,291,36,12,avg,1.39,271.0,17.0,11.0,2.0,6.0,76.0,168.0,38.0,3.0,2.0,1.0
2,2498,95056,226424,6,36,23,avg,1.30,184.0,12.0,8.0,3.0,4.0,65.0,131.0,23.0,2.0,1.0,1.0
3,2498,95056,226424,210,36,26,avg,1.11,243.0,16.0,11.0,4.0,5.0,65.0,163.0,34.0,1.0,1.0,0.0
4,2498,95056,226424,227,36,21,avg,0.65,81.0,4.0,9.0,6.0,-5.0,82.0,57.0,31.0,0.0,1.0,-1.0

In [46]:
df.to_sql(
    "silver_fact_players",
    conn,
    if_exists="replace",
    index=False
)

96915

In [201]:
query = """
WITH round_score AS (
    SELECT DISTINCT
        match_id,
        SUM (home_score) OVER (PARTITION BY match_id) AS home_total_round,
        SUM (away_score) OVER (PARTITION BY match_id) AS away_total_round
    FROM silver_fact_games
)
SELECT
    tour_id,
    m.match_id,
    date,
    bracket,
    patch_id,
    home_team_id,
    away_team_id,
    bo,
    home_score,
    away_score,
    ROUND ((1.0 * home_score - away_score) / (1.0 * home_score + away_score), 2) AS match_score_diff_pct,
    r.home_total_round AS home_total_round,
    r.away_total_round AS away_total_round,
    ROUND ((1.0 * home_total_round - away_total_round) / (1.0 * home_total_round + away_total_round), 2) AS match_round_diff_pct,
    home_h2h_win,
    away_h2h_win,
    ROUND ((1.0 * home_h2h_win - away_h2h_win) / (1.0 * home_h2h_win + away_h2h_win)) AS h2h_win_pct,
    home_h2h_score,
    away_h2h_score,
    ROUND ((1.0 * home_h2h_score - away_h2h_score) / (1.0 * home_h2h_score + away_h2h_score), 2) AS h2h_game_win_pct,
    home_n_last_win,
    away_n_last_win,
    home_n_last_match,
    away_n_last_match,
    away_n_last_wr,
    (CASE WHEN home_score > away_score THEN 1 ELSE 0 END) as is_home_win
FROM silver_fact_matches m
JOIN round_score r
ON r.match_id = m.match_id
"""

df = pd.read_sql(query, conn)
df.head()

,tour_id,match_id,date,bracket,patch_id,home_team_id,away_team_id,bo,home_score,away_score,...,h2h_win_pct,home_h2h_score,away_h2h_score,h2h_game_win_pct,home_n_last_win,away_n_last_win,home_n_last_match,away_n_last_match,away_n_last_wr,is_home_win
0,2498,95056,2025-07-16 11:00:00,Group Stage: Week 1,9,36,4,Bo3,2,1,...,1.0,2,1,0.33,3,0,5,5,0.0,1
1,2498,95057,2025-07-16 13:50:00,Group Stage: Week 1,9,49,22,Bo3,0,2,...,1.0,6,2,0.50,1,2,5,5,0.4,0
2,2498,95058,2025-07-17 11:00:00,Group Stage: Week 1,9,19,24,Bo3,2,1,...,1.0,4,1,0.60,2,4,5,5,0.8,1
3,2498,95059,2025-07-17 14:30:00,Group Stage: Week 1,9,47,29,Bo3,2,1,...,1.0,11,4,0.47,1,1,5,5,0.2,1
4,2498,95060,2025-07-18 11:00:00,Group Stage: Week 1,9,46,5,Bo3,2,1,...,0.0,7,4,0.27,5,4,5,5,0.8,1

In [202]:
df.to_sql(
    "gold_fact_matches",
    conn,
    if_exists="replace",
    index=False
)

1259

In [208]:
query = """ -- NULLIF doesn't apply yet
SELECT
    tour_id,
    match_id,
    game_id,
    map_id,
    home_team_id,
    away_team_id,
    game_duration,
    home_score,
    away_score,
    ROUND ((1.0 * home_score - away_score) / (1.0 * home_score + away_score), 2) AS round_diff_pct,
    home_atk_score,
    away_atk_score,
    home_def_score,
    away_def_score,
    ROUND ((1.0 * home_atk_score / (home_atk_score + away_def_score)) / (1.0 * away_atk_score / (away_atk_score + home_def_score)), 2) AS atk_wr_diff,
    ROUND ((1.0 * home_def_score / (home_def_score + away_atk_score)) / (1.0 * away_def_score / (away_def_score + home_atk_score)), 2) AS def_wr_diff,
    home_ot_score,
    away_ot_score,
    home_ot_score + away_ot_score AS ot_total_round,
    ROUND ((home_ot_score - away_ot_score) / (home_ot_score + away_ot_score), 2) AS ot_score_diff_pct,
    home_pstl_win,
    away_pstl_win,
    home_pstl_win - away_pstl_win AS pstl_score_diff,
    home_eco_round,
    away_eco_round,
    home_eco_round - away_eco_round AS eco_round_diff,
    home_eco_win,
    away_eco_win,
    home_eco_win - away_eco_win AS eco_win_diff,
    ROUND ((home_eco_win / home_eco_round) - (away_eco_win / away_eco_round), 2) AS eco_diff_pct,
    home_semi_eco_round,
    away_semi_eco_round,
    home_semi_eco_round - away_semi_eco_round AS semi_eco_round_diff,
    home_semi_eco_win,
    away_semi_eco_win,
    home_semi_eco_win - away_semi_eco_win AS semi_eco_win_diff,
    ROUND ((home_semi_eco_win / home_semi_eco_round) - (away_semi_eco_win / away_semi_eco_round), 2) AS semi_eco_diff_pct,
    home_semi_buy_round,
    away_semi_buy_round,
    home_semi_buy_round - away_semi_buy_round AS semi_buy_round_diff,
    home_semi_buy_win,
    away_semi_buy_win,
    home_semi_buy_win - away_semi_buy_win AS semi_buy_win_diff,
    ROUND ((home_semi_buy_win / home_semi_buy_round) - (away_semi_buy_win / away_semi_buy_round), 2) AS semi_buy_diff_pct,
    home_full_buy_round,
    away_full_buy_round,
    home_full_buy_round - away_full_buy_round AS full_buy_round_diff,
    home_full_buy_win,
    away_full_buy_win,
    home_full_buy_win - away_full_buy_win AS full_buy_win_diff,
    ROUND ((home_full_buy_win / home_full_buy_round) - (away_full_buy_win / away_full_buy_round), 2) AS full_buy_diff_pct,
    (CASE WHEN home_score > away_score THEN 1 ELSE 0 END) as is_home_win
FROM silver_fact_games
"""

df = pd.read_sql(query, conn)
df.head()

,tour_id,match_id,game_id,map_id,home_team_id,away_team_id,game_duration,home_score,away_score,round_diff_pct,...,semi_buy_win_diff,semi_buy_diff_pct,home_full_buy_round,away_full_buy_round,full_buy_round_diff,home_full_buy_win,away_full_buy_win,full_buy_win_diff,full_buy_diff_pct,is_home_win
0,2498,95056,226424,8,36,4,37.88,13,4,0.53,...,-1.0,0.25,11.0,4.0,7.0,10.0,1.0,9.0,0.66,1
1,2498,95056,226425,12,36,4,40.00,6,13,-0.37,...,-4.0,-0.50,11.0,10.0,1.0,5.0,5.0,0.0,-0.05,0
2,2498,95056,226426,5,36,4,37.05,13,3,0.63,...,1.0,0.67,11.0,4.0,7.0,8.0,1.0,7.0,0.48,1
3,2498,95057,226427,12,49,22,51.33,10,13,-0.13,...,4.0,-0.17,13.0,17.0,-4.0,3.0,11.0,-8.0,-0.42,0
4,2498,95057,226428,3,49,22,52.45,11,13,-0.08,...,-3.0,0.00,16.0,10.0,6.0,8.0,6.0,2.0,-0.10,0

In [210]:
df.to_sql(
    "gold_fact_games",
    conn,
    if_exists="replace",
    index=False
)

3224

In [ ]:
conn.execute("""DROP VIEW IF EXISTS gold_view_team_game_statistics""")

query = """
CREATE VIEW gold_view_team_game_statistics AS
SELECT
    tour_id,
    match_id,
    game_id,
    map_id,
    home_team_id AS team_id,
    (CASE WHEN ot_total_round > 0 THEN 1 ELSE 0 END) AS is_ot,
    is_home_win AS is_win,
    game_duration,
    round_diff_pct,
    ROUND (home_atk_score * 1.0 / NULLIF(home_atk_score + away_def_score, 0), 2) AS atk_wr,
    ROUND (home_def_score * 1.0 / NULLIF(home_def_score + away_atk_score, 0), 2) AS def_wr,
    ROUND (home_pstl_win * 1.0 / NULLIF(home_pstl_win + away_pstl_win, 0), 2) AS pstl_wr,
    ROUND (home_eco_win * 1.0 / NULLIF(home_eco_round, 0), 2) AS eco_wr,
    ROUND (home_semi_eco_win * 1.0 / NULLIF(home_semi_eco_round, 0), 2) AS semi_eco_wr,
    ROUND (home_semi_buy_win * 1.0 / NULLIF(home_semi_buy_round, 0), 2) AS semi_buy_wr,
    ROUND (home_full_buy_win * 1.0 / NULLIF(home_full_buy_round, 0), 2) AS full_buy_wr
FROM gold_fact_games
UNION
SELECT
    tour_id,
    match_id,
    game_id,
    map_id,
    away_team_id,
    (CASE WHEN ot_total_round > 0 THEN 1 ELSE 0 END),
    (CASE WHEN is_home_win = 1 THEN 0 ELSE 1 END) AS is_win,
    game_duration,
    round_diff_pct * (-1.0),
    ROUND (away_atk_score * 1.0 / NULLIF(home_def_score + away_atk_score, 0), 2),
    ROUND (away_def_score * 1.0 / NULLIF(home_atk_score + away_def_score, 0), 2),
    ROUND (away_pstl_win * 1.0 / NULLIF(home_pstl_win + away_pstl_win, 0), 2),
    ROUND (away_eco_win * 1.0 / NULLIF(away_eco_round, 0), 2),
    ROUND (away_semi_eco_win * 1.0 / NULLIF(away_semi_eco_round, 0), 2),
    ROUND (away_semi_buy_win * 1.0 / NULLIF(away_semi_buy_round, 0), 2),
    ROUND (away_full_buy_win * 1.0 / NULLIF(away_full_buy_round, 0), 2)
FROM gold_fact_games
"""

conn.execute(query)
conn.commit()

# df = pd.read_sql(query, conn)
# df

In [ ]:
conn.execute("""DROP TABLE IF EXISTS gold_fact_map_vetos""")

query = """
CREATE TABLE gold_fact_map_vetos AS
SELECT
    v.match_id,
    m.home_team_id AS team_id,
    ma.map_id,
    action,
    (CASE WHEN action = "decider" THEN NULL ELSE 0 END) AS action_order
FROM silver_map_vetos v
JOIN silver_dims_maps ma
ON v.map_name = ma.map_name
JOIN silver_fact_matches m
ON v.match_id = m.match_id
WHERE action = "decider"
UNION
SELECT
    v.match_id,
    m.away_team_id,
    ma.map_id,
    action,
    (CASE WHEN action = "decider" THEN NULL ELSE 0 END)
FROM silver_map_vetos v
JOIN silver_dims_maps ma
ON v.map_name = ma.map_name
JOIN silver_fact_matches m
ON v.match_id = m.match_id
WHERE action = "decider";
"""

conn.execute(query)
conn.commit()

# df = pd.read_sql(query, conn)
# df

In [ ]:
query = """
INSERT INTO gold_fact_map_vetos (match_id, team_id, map_id, action, action_order)
SELECT
    match_id,
    t.team_id,
    m.map_id,
    action,
    IFNULL(ROW_NUMBER () OVER (PARTITION BY match_id, team_id, action ORDER BY match_id), 0)
FROM silver_map_vetos v
JOIN silver_dims_teams t
ON t.team_alias = v.team_name
JOIN silver_dims_maps m
ON m.map_name = v.map_name
WHERE NOT v.team_name = "None";
"""

conn.execute(query)
conn.commit()

# df = pd.read_sql(query, conn)
# df

In [3]:
conn.execute("DROP VIEW IF EXISTS gold_view_team_map_statistics")

query = """
CREATE VIEW gold_view_team_map_statistics AS
WITH team_map_count AS (
    SELECT
        v.team_id,
        v.map_id,
        t1.total_matches,
        t2.total_win,

        SUM (CASE
            WHEN action = "pick"
            THEN 1
            ELSE 0
            END) AS pick_count,
        SUM (CASE
            WHEN action = "ban"
            THEN 1
            ELSE 0
            END) AS ban_count
    FROM gold_fact_map_vetos v
    JOIN (
    SELECT team_id, COUNT (DISTINCT match_id) AS total_matches
    FROM gold_view_team_game_statistics
    GROUP BY team_id
    ) t1
    ON v.team_id = t1.team_id
    JOIN (
    SELECT team_id, map_id, SUM (is_win) AS total_win
    FROM gold_view_team_game_statistics
    GROUP BY team_id, map_id
    ) t2
    ON v.team_id = t2.team_id
    AND v.map_id = t2.map_id
    GROUP BY v.team_id, v.map_id
),
team_map_rate AS (
    SELECT
        team_id,
        map_id,
        total_win,
        pick_count,
        ban_count,
        ROUND (1.0 * pick_count / total_matches, 2) AS pick_rate,
        ROUND (1.0 * ban_count / total_matches, 2) AS ban_rate,
        ROUND (1.0 * pick_count / (pick_count + ban_count), 2) AS map_pick_preference
    FROM team_map_count
)

SELECT
    s.team_id,
    s.map_id,
    COUNT (*) AS total_map_played,
    SUM (is_ot) AS total_ot_played,
    c.total_win,
    ROUND (1.0 * c.total_win / count (*), 2) as map_wr,
    c.pick_count,
    c.ban_count,
    c.pick_rate,
    c.ban_rate,
    c.map_pick_preference,
    ROUND (AVG (game_duration), 2) AS avg_game_duration,
    ROUND (AVG (round_diff_pct), 2) AS avg_round_diff_pct,
    ROUND (AVG (atk_wr), 2) AS avg_atk_wr,
    ROUND (AVG (def_wr), 2) AS avg_def_wr,
    ROUND (AVG (pstl_wr), 2) AS avg_pstl_wr,
    ROUND (AVG (eco_wr), 2) AS avg_eco_wr,
    ROUND (AVG (semi_eco_wr), 2) AS avg_semi_eco_wr,
    ROUND (AVG (semi_buy_wr), 2) AS avg_semi_buy_wr,
    ROUND (AVG (full_buy_wr), 2) AS avg_full_buy_wr
FROM gold_view_team_game_statistics s
JOIN team_map_rate c
ON s.team_id = c.team_id
AND s.map_id = c.map_id
GROUP BY s.team_id, s.map_id
;
"""

conn.execute(query)
conn.commit()

# df = pd.read_sql(query, conn)
# df

In [5]:
df = pd.read_sql("""
SELECT *
FROM gold_view_team_map_statistics
""", conn)
df.head(df["map_id"].nunique())

,team_id,map_id,total_map_played,total_ot_played,total_win,map_wr,pick_count,ban_count,pick_rate,ban_rate,map_pick_preference,avg_game_duration,avg_round_diff_pct,avg_atk_wr,avg_def_wr,avg_pstl_wr,avg_eco_wr,avg_semi_eco_wr,avg_semi_buy_wr,avg_full_buy_wr
0,1,1,3,0,1,0.33,1,8,0.02,0.16,0.11,46.73,0.12,0.56,0.59,0.33,0.22,0.00,0.75,0.63
1,1,2,8,1,6,0.75,1,8,0.02,0.16,0.11,53.73,0.24,0.61,0.63,0.71,0.63,0.17,0.55,0.71
2,1,3,27,3,16,0.59,22,1,0.43,0.02,0.96,53.98,0.12,0.59,0.53,0.56,0.48,0.17,0.68,0.57
3,1,4,4,0,3,0.75,1,8,0.02,0.16,0.11,54.73,0.18,0.60,0.63,0.33,0.22,0.33,0.76,0.61
4,1,5,5,1,4,0.80,1,4,0.02,0.08,0.20,52.15,0.25,0.61,0.63,0.70,0.53,0.67,0.64,0.64
5,1,6,3,0,2,0.67,2,1,0.04,0.02,0.67,53.28,0.15,0.61,0.56,0.50,0.53,0.50,0.52,0.59
6,1,7,13,1,6,0.46,8,9,0.16,0.18,0.47,50.92,-0.09,0.47,0.44,0.50,0.38,0.09,0.55,0.48
7,1,8,16,3,8,0.50,5,8,0.10,0.16,0.38,52.81,0.07,0.53,0.54,0.42,0.39,0.37,0.61,0.55
8,1,9,9,2,4,0.44,2,30,0.04,0.59,0.06,55.56,-0.11,0.49,0.36,0.44,0.36,0.17,0.53,0.47
9,1,10,9,3,3,0.33,4,8,0.08,0.16,0.33,57.33,-0.08,0.45,0.46,0.28,0.25,0.19,0.52,0.54
10,1,11,18,2,10,0.56,2,5,0.04,0.10,0.29,51.61,0.01,0.50,0.51,0.33,0.30,0.11,0.51,0.60
11,1,12,9,1,2,0.22,3,12,0.06,0.24,0.20,46.94,-0.22,0.36,0.39,0.36,0.32,0.50,0.44,0.48

In [38]:
conn.execute("DROP VIEW IF EXISTS gold_view_map_statistics")

query = """
CREATE VIEW gold_view_map_statistics AS
WITH map_count AS (
    SELECT
        v.map_id,
        m1.total_map_played,
        m2.total_matches,

        SUM (CASE
            WHEN action = "pick"
            THEN 1
            ELSE 0
            END) AS pick_count,
        SUM (CASE
            WHEN action = "ban"
            THEN 1
            ELSE 0
            END) AS ban_count
    FROM gold_fact_map_vetos v
    JOIN (
    SELECT map_id, COUNT (DISTINCT match_id) AS total_map_played
    FROM gold_view_team_game_statistics
    GROUP BY map_id
    ) m1
    ON v.map_id = m1.map_id
    JOIN (
        SELECT COUNT (DISTINCT match_id) AS total_matches
        FROM gold_view_team_game_statistics
    ) m2
    GROUP BY v.map_id
),
map_rate AS (
    SELECT
        map_id,
        total_map_played,
        pick_count,
        ban_count,
        ROUND (1.0 * pick_count / total_matches, 2) AS pick_rate,
        ROUND (1.0 * ban_count / total_matches, 2) AS ban_rate
    FROM map_count
)

SELECT
    s.map_id,
    c.total_map_played,
    SUM (is_ot) AS total_ot_played,
    c.pick_count,
    c.ban_count,
    c.pick_rate,
    c.ban_rate,
    ROUND (AVG (game_duration), 2) AS avg_game_duration,
    ROUND (AVG (atk_wr), 2) AS avg_atk_wr, -- unvalid definition for atk win rate for a map
    ROUND (AVG (def_wr), 2) AS avg_def_wr -- unvalid definition for atk win rate for a map
FROM gold_view_team_game_statistics s
JOIN map_rate c
ON s.map_id = c.map_id
GROUP BY s.map_id
"""

conn.execute(query)
conn.commit()


# df = pd.read_sql(query, conn)
# df

In [12]:
df = pd.read_sql("""
SELECT *
FROM gold_view_map_statistics
""", conn)
df.head(df["map_id"].nunique())

,map_id,total_map_played,total_ot_played,pick_count,ban_count,pick_rate,ban_rate,avg_game_duration,avg_atk_wr,avg_def_wr
0,1,143,32,132,181,0.10,0.14,52.75,0.54,0.46
1,2,295,52,235,537,0.19,0.43,51.33,0.49,0.51
2,3,356,88,295,570,0.23,0.45,53.46,0.52,0.48
3,4,172,24,139,341,0.11,0.27,50.82,0.51,0.50
4,5,115,24,99,207,0.08,0.16,51.09,0.51,0.50
5,6,138,34,115,293,0.09,0.23,51.88,0.52,0.48
6,7,356,72,295,528,0.23,0.42,51.18,0.52,0.48
7,8,285,72,247,465,0.20,0.37,51.19,0.53,0.47
8,9,527,124,449,502,0.36,0.40,53.26,0.52,0.48
9,10,211,56,173,379,0.14,0.30,55.34,0.49,0.51
10,11,359,82,280,528,0.22,0.42,53.32,0.50,0.50
11,12,267,46,223,341,0.18,0.27,50.32,0.51,0.49

In [49]:
conn.execute("DROP VIEW IF EXISTS gold_fact_players")

query = """
CREATE VIEW gold_fact_players AS
SELECT
    p.tour_id,
    p.match_id,
    p.game_id,
    s.map_id,
    player_id,
    p.team_id,
    agent_id,
    s.is_win,
    mod,
    r,
    acs,
    k,
    d,
    a,
    kd,
    kast,
    adr,
    hs,
    fk,
    fd,
    fkfd
FROM silver_fact_players p
JOIN gold_view_team_game_statistics s
ON p.game_id = s.game_id
AND p.team_id = s.team_id;
"""

conn.execute(query)
conn.commit()

# df = pd.read_sql(query, conn)
# df

In [52]:
df = pd.read_sql("""
SELECT *
FROM gold_fact_players
""", conn)
df.head()

,tour_id,match_id,game_id,map_id,player_id,team_id,agent_id,is_win,mod,r,...,k,d,a,kd,kast,adr,hs,fk,fd,fkfd
0,2498,95056,226424,8,351,36,14,1,avg,1.69,...,19.0,7.0,3.0,12.0,76.0,183.0,39.0,4.0,2.0,2.0
1,2498,95056,226424,8,291,36,12,1,avg,1.39,...,17.0,11.0,2.0,6.0,76.0,168.0,38.0,3.0,2.0,1.0
2,2498,95056,226424,8,6,36,23,1,avg,1.30,...,12.0,8.0,3.0,4.0,65.0,131.0,23.0,2.0,1.0,1.0
3,2498,95056,226424,8,210,36,26,1,avg,1.11,...,16.0,11.0,4.0,5.0,65.0,163.0,34.0,1.0,1.0,0.0
4,2498,95056,226424,8,227,36,21,1,avg,0.65,...,4.0,9.0,6.0,-5.0,82.0,57.0,31.0,0.0,1.0,-1.0

In [53]:
conn.execute("DROP VIEW IF EXISTS gold_view_average_player_statistics")

query = """
CREATE VIEW gold_view_average_player_statistics AS
SELECT
    player_id,
    COUNT (*) AS games_played,
    ROUND (AVG (r), 2) AS avg_r,
    ROUND (AVG (acs), 2) AS avg_acs,
    ROUND (AVG (k), 2) AS avg_k,
    ROUND (AVG (d), 2) AS avg_d,
    ROUND (AVG (a), 2) AS avg_a,
    ROUND (AVG (kd), 2) AS avg_kd,
    ROUND (AVG (kast), 2) AS avg_kast,
    ROUND (AVG (adr), 2) AS avg_adr,
    ROUND (AVG (hs), 2) AS avg_hs,
    ROUND (AVG (fk), 2) AS avg_fk,
    ROUND (AVG (fd), 2) AS avg_fd,
    ROUND (AVG (fkfd), 2) AS avg_fkfd
FROM gold_fact_players
WHERE mod = "avg"
GROUP BY player_id;
"""

conn.execute(query)
conn.commit()


# df = pd.read_sql(query, conn)
# df

In [54]:
df = pd.read_sql("""
SELECT *
FROM gold_view_average_player_statistics
""", conn)
df.head()

,player_id,games_played,avg_r,avg_acs,avg_k,avg_d,avg_a,avg_kd,avg_kast,avg_adr,avg_hs,avg_fk,avg_fd,avg_fkfd
0,1,34,0.92,174.71,12.76,14.53,7.00,-1.76,69.88,112.76,25.26,1.50,2.00,-0.50
1,2,15,0.83,163.67,11.07,15.33,5.60,-4.27,68.67,119.67,22.50,2.33,2.33,0.00
2,3,135,1.05,198.00,15.51,14.27,4.95,1.24,71.38,131.47,38.05,1.33,1.06,0.27
3,4,19,NaN,208.37,15.47,15.63,3.74,-0.16,NaN,109.00,26.50,1.00,2.50,-1.50
4,5,25,NaN,201.56,15.24,14.68,7.72,0.56,NaN,135.00,27.75,1.33,1.58,-0.25

In [3]:
conn.execute("DROP VIEW IF EXISTS gold_view_average_player_agent_statistics")

query = """
CREATE VIEW gold_view_average_player_agent_statistics AS
-- WITH team_game_wr AS ()
SELECT
    player_id,
    agent_id,
    COUNT (*) AS games_played,
    SUM(is_win) AS total_win,
    ROUND (1.0 * SUM (is_win) / COUNT (*), 2) AS agent_wr,
    ROUND (AVG (r), 2) AS avg_r,
    ROUND (AVG (acs), 2) AS avg_acs,
    ROUND (AVG (k), 2) AS avg_k,
    ROUND (AVG (d), 2) AS avg_d,
    ROUND (AVG (a), 2) AS avg_a,
    ROUND (AVG (kd), 2) AS avg_kd,
    ROUND (AVG (kast), 2) AS avg_kast,
    ROUND (AVG (adr), 2) AS avg_adr,
    ROUND (AVG (hs), 2) AS avg_hs,
    ROUND (AVG (fk), 2) AS avg_fk,
    ROUND (AVG (fd), 2) AS avg_fd,
    ROUND (AVG (fkfd), 2) AS avg_fkfd
FROM gold_fact_players
WHERE mod = "avg"
GROUP BY player_id, agent_id;
"""

conn.execute(query)
conn.commit()

# df = pd.read_sql(query, conn)
# df

In [24]:
df = pd.read_sql("""
SELECT *
FROM gold_view_average_player_agent_statistics
""", conn)
df.head()

,player_id,agent_id,games_played,total_win,agent_wr,avg_r,avg_acs,avg_k,avg_d,avg_a,avg_kd,avg_kast,avg_adr,avg_hs,avg_fk,avg_fd,avg_fkfd
0,1,1,6,1,0.17,0.80,162.83,11.00,13.83,6.83,-2.83,69.00,100.00,20.33,2.17,2.67,-0.50
1,1,3,1,0,0.00,0.47,123.00,5.00,15.00,5.00,-10.00,33.00,86.00,17.00,0.00,0.00,0.00
2,1,17,21,10,0.48,0.99,178.52,13.38,14.38,7.71,-1.00,72.95,113.57,25.86,1.62,1.90,-0.29
3,1,26,6,3,0.50,0.87,181.83,13.67,15.67,5.00,-2.00,66.17,127.17,29.50,0.67,2.00,-1.33
4,2,1,1,0,0.00,NaN,174.00,11.00,16.00,4.00,-5.00,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
conn.execute("DROP VIEW IF EXISTS gold_view_average_player_agent_map_statistics")

query = """
CREATE VIEW gold_view_average_player_agent_map_statistics AS
SELECT
    player_id,
    agent_id,
    map_id,
    COUNT (*) AS games_played,
    ROUND (1.0 * SUM (is_win) / COUNT (*), 2) AS agent_wr,
    ROUND (AVG (r), 2) AS avg_r,
    ROUND (AVG (acs), 2) AS avg_acs,
    ROUND (AVG (k), 2) AS avg_k,
    ROUND (AVG (d), 2) AS avg_d,
    ROUND (AVG (a), 2) AS avg_a,
    ROUND (AVG (kd), 2) AS avg_kd,
    ROUND (AVG (kast), 2) AS avg_kast,
    ROUND (AVG (adr), 2) AS avg_adr,
    ROUND (AVG (hs), 2) AS avg_hs,
    ROUND (AVG (fk), 2) AS avg_fk,
    ROUND (AVG (fd), 2) AS avg_fd,
    ROUND (AVG (fkfd), 2) AS avg_fkfd
FROM gold_fact_players
WHERE mod = "avg"
GROUP BY player_id, agent_id, map_id;
"""

conn.execute(query)
conn.commit()

# df = pd.read_sql(query, conn)
# df

In [71]:
df = pd.read_sql("""
SELECT *
FROM gold_view_average_player_agent_map_statistics
""", conn)
df.head()

,player_id,agent_id,map_id,games_played,agent_wr,avg_r,avg_acs,avg_k,avg_d,avg_a,avg_kd,avg_kast,avg_adr,avg_hs,avg_fk,avg_fd,avg_fkfd
0,1,1,7,1,0.00,1.07,232.00,17.0,18.00,10.0,-1.00,77.0,140.00,17.0,5.0,1.00,4.00
1,1,1,10,4,0.25,0.79,161.25,10.5,12.75,6.5,-2.25,70.5,98.75,22.0,1.5,2.75,-1.25
2,1,1,11,1,0.00,0.55,100.00,7.0,14.00,5.0,-7.00,55.0,65.00,17.0,2.0,4.00,-2.00
3,1,3,6,1,0.00,0.47,123.00,5.0,15.00,5.0,-10.00,33.0,86.00,17.0,0.0,0.00,0.00
4,1,17,1,2,0.50,1.15,214.00,14.5,13.50,8.0,1.00,85.5,137.50,21.5,1.5,1.50,0.00

In [10]:
conn.execute("DROP VIEW IF EXISTS gold_view_agent_statistics")

query = """
CREATE VIEW gold_view_agent_statistics AS
WITH game_count AS (
    SELECT
        COUNT(DISTINCT match_id) AS game_count
    FROM gold_fact_players
),
agent_presence_count AS (
    SELECT
        agent_id,
        COUNT (*) AS game_presence
    FROM (
        SELECT
            game_id,
            agent_id
        FROM gold_fact_players
        WHERE mod = "avg"
        GROUP BY game_id, agent_id
    )
    GROUP BY agent_id
)
SELECT
    p.agent_id,
    COUNT (*) AS pick_count,
    a.game_presence as game_presence_count,
    c.game_count,
    SUM (is_win) AS win_count,
    ROUND (1.0 * a.game_presence / c.game_count, 2) AS agent_presence_rate,
    ROUND (1.0 * COUNT(*) / c.game_count, 2) AS agent_pick_rate,
    ROUND (1.0 * SUM (is_win) / COUNT (*), 2) AS agent_win_rate
FROM gold_fact_players p
JOIN game_count c
JOIN agent_presence_count a
ON p.agent_id = a.agent_id
WHERE mod = "avg"
GROUP BY p.agent_id;
"""

conn.execute(query)
conn.commit()

# df = pd.read_sql(query, conn)
# df

In [34]:
df = pd.read_sql("""
SELECT *
FROM gold_view_agent_statistics
""", conn)
df.head()

,agent_id,pick_count,game_presence_count,game_count,win_count,agent_presence_rate,agent_pick_rate,agent_win_rate
0,1,1131,794,1259,562,0.63,0.90,0.50
1,2,1231,911,1259,574,0.72,0.98,0.47
2,3,862,513,1259,439,0.41,0.68,0.51
3,4,380,354,1259,200,0.28,0.30,0.53
4,5,75,74,1259,41,0.06,0.06,0.55

In [38]:
conn.execute("DROP VIEW IF EXISTS gold_view_agent_map_statistics")

query = """
CREATE VIEW gold_view_agent_map_statistics AS

WITH agent_map_count AS (
    SELECT
        agent_id,
        map_id,
        COUNT (*) AS agent_map_presence
    FROM (
        SELECT
            game_id,
            agent_id,
            map_id
        FROM gold_fact_players
        WHERE mod = "avg"
        GROUP BY game_id, agent_id, map_id
    )
    GROUP BY agent_id, map_id
)
SELECT
    p.agent_id,
    p.map_id,
    a.agent_map_presence AS agent_map_presence_count,
    COUNT (*) AS pick_count,
    SUM (is_win) AS win_count,
    ROUND (1.0 * SUM (is_win) / COUNT (*), 2) AS agent_win_rate,
    ROUND (1.0 * a.agent_map_presence / s.total_map_played, 2) AS agent_map_presence_rate
FROM gold_fact_players p
JOIN agent_map_count a
ON p.agent_id = a.agent_id
AND p.map_id = a.map_id
JOIN gold_view_map_statistics s
ON p.map_id = s.map_id
WHERE mod = "avg"
GROUP BY p.agent_id, p.map_id;
"""

conn.execute(query)
conn.commit()

# df = pd.read_sql(query, conn)
# df

In [44]:
# invalid decider value for match_id, the correct one is Lotus. Check Liquipedia.
df = pd.read_sql("""
SELECT *, COUNT(*)
FROM gold_view_agent_statistics
GROUP BY agent_id
-- HAVING COUNT(*) > 1
""", conn)
df

,agent_id,pick_count,game_presence_count,game_count,win_count,agent_presence_rate,agent_pick_rate,agent_win_rate,COUNT(*)
0,1,1131,794,1259,562,0.63,0.90,0.50,1
1,2,1231,911,1259,574,0.72,0.98,0.47,1
2,3,862,513,1259,439,0.41,0.68,0.51,1
3,4,380,354,1259,200,0.28,0.30,0.53,1
4,5,75,74,1259,41,0.06,0.06,0.55,1
5,6,2020,1466,1259,1003,1.16,1.60,0.50,1
6,7,279,263,1259,128,0.21,0.22,0.46,1
7,8,1774,1272,1259,890,1.01,1.41,0.50,1
8,9,728,576,1259,354,0.46,0.58,0.49,1
9,10,295,261,1259,142,0.21,0.23,0.48,1
10,11,153,143,1259,75,0.11,0.12,0.49,1
11,12,1677,1176,1259,834,0.93,1.33,0.50,1
12,13,1224,951,1259,604,0.76,0.97,0.49,1
13,14,1595,1080,1259,807,0.86,1.27,0.51,1
14,15,2,2,1259,0,0.00,0.00,0.00,1
15,16,1573,1136,1259,788,0.90,1.25,0.50,1
16,17,3902,2196,1259,1938,1.74,3.10,0.50,1
17,18,221,200,1259,120,0.16,0.18,0.54,1
18,19,2179,1399,1259,1111,1.11,1.73,0.51,1
19,20,57,57,1259,25,0.05,0.05,0.44,1
20,21,249,233,1259,134,0.19,0.20,0.54,1
21,22,990,714,1259,497,0.57,0.79,0.50,1
22,23,2563,1631,1259,1288,1.30,2.04,0.50,1
23,24,872,662,1259,430,0.53,0.69,0.49,1
24,25,72,66,1259,33,0.05,0.06,0.46,1
25,26,3251,2008,1259,1652,1.59,2.58,0.51,1
26,27,730,597,1259,366,0.47,0.58,0.50,1
27,28,639,492,1259,315,0.39,0.51,0.49,1
28,29,1581,1206,1259,798,0.96,1.26,0.50,1

In [406]:
conn.close()